### ISSUE TITLE
master branch not being pulled 

### ISSUE THREAD

**Issue by moreaujean** [bmulvihill/apriori#5]
It looks like a non-master branch of your gem is pulled when I include apriori-gem in my Gemfile. There's an error that references the method 'initial_data_set' which is not found in your master branch.

**Comment by bmulvihill** [comment]
Ahh thanks for noticing I'll fix this

**Comment by bmulvihill** [comment]
I forgot to push the latest version to ruby gems, if you bundle update you should be good to go!  Thanks
